[variables]
NODE_VERSION = "20"
PNPM_VERSION = "10"
SKIP_ENV_VALIDATION = "true"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile --production=false"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm start"
